### ISSUE TITLE
Lancer le debugger dans le code destinie

### ISSUE THREAD

**Issue by guillett** [InseeFr/Destinie-2#2]
Bonjour et merci :)

C'est vraiment génial de voir qu'une partie du code financé par l'argent public soit publié et redonner aux citoyens !

Je cherche modifier le code de Destinie pour évaluer l'impact du projet de la réforme des retraites.
J'avance à tâtons car le code est très complet et contient pas mal de complexité.

J'ai tenté d'afficher des valeurs depuis le code C++ mais cela nécessite de recompiler Destinie à chaque itération (ce qui prend plusieurs secondes et donc n'est pas très pratique).

Avez-vous réussi à lancer Destinie avec un debugger, par exemple avec la commande suivante ou une commande similaire `R -d gdb -f demo/simulation.R` ?

Dans mon cas, après avoir lancer le script (écrire 'r' dans gdb), le programme échout à la ligne `library(destinie)` avec le message suivant :
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffca9ed51b in ?? ()
```

Encore merci !

**Comment by ACL90** [comment]
Bonjour,
Plusieurs éléments informatifs, dont certains de mémoire:
- L'Insee a commencé dès 2016 à mettre en libre accès un de ses modèles (Ines, partagé avec le ministère de la santé). Cela lui est devenu obligatoire depuis octobre 2018 du fait de la loi Lemaire. Les liens vers les modèles Insee sont présentés ici: https://www.insee.fr/fr/information/2021959
- Le code du modèle Destinie est en effet assez complexe. Nous l'avons cependant fortement documenté lors de la mise en ligne, voir la documentation dans le répertoire: https://github.com/InseeFr/Destinie-2/tree/release_ssparam/documentation
- L'usage était l'année dernière (et est probablement encore) de recompiler. C'est en effet assez long si vous avez modifié un fichier ".h" (ce qui n'est en général pas très fréquent), mais raisonnable sinon. Cependant, si vous proposez une solution technique, n'hésitez surtout pas à la partager: tout le monde en bénéficiera ainsi.
Alexandre
(anciennement dans l'équipe Destinie)

**Comment by guillett** [comment]
Super, merci pour ces infos ! Je ferme l'issue.
